# These are supported funding model platforms

github: [VaheSaroyan]
patreon: vahesaroyan
open_collective: # Replace with a single Open Collective username
ko_fi:VaheSaroyan
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: VaheSaroyan/react-native-boilerplate
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: [VaheSaroyan]
